### ISSUE TITLE
Specifying `edit-only` vs. `generate` mode

### ISSUE THREAD

**Issue by RobotSail** [redhat-et/copilot-ops#17]
Related to #16, the Codex `/edits` endpoint will only edit files in-place based on the provided input, but it does not provide new additions in terms of new files.

For example, the following prompt + input works as expected:

`files`:
```yaml
# @kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
    - namespace.yaml
    - resourcequota.yaml
components:
    - ../../../../components/project-admin-rolebindings/octo-training-model
    - ../../../../components/limitranges/default
namespace: training-model
```

`input`:
```md
@kustomization needs to add `globalresources.yaml` to its `.resources` field.
```

Produces the output:
```yaml
# @kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
    - namespace.yaml
    - resourcequota.yaml
    - globalresources.yaml
components:
    - ../../../../components/project-admin-rolebindings/octo-training-model
    - ../../../../components/limitranges/default
namespace: training-model
```

However, specifying the following only produces changes to `@kustomization` and doesn't generate the newly requested resource:

`files`:
```yaml
# @kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
    - namespace.yaml
    - resourcequota.yaml
components:
    - ../../../../components/project-admin-rolebindings/octo-training-model
    - ../../../../components/limitranges/default
namespace: training-model
```

`input`
```md
@kustomization needs to add `globalresources.yaml` to its `.resources` field.

We also need to create a new ConfigMap tagged `@configmap` containing a username and password for the model to pull from and use as authentication for the dataset
```

Produces:
```yaml
# @kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
    - namespace.yaml
    - resourcequota.yaml
    - globalresources.yaml
components:
    - ../../../../components/project-admin-rolebindings/octo-training-model
    - ../../../../components/limitranges/default
namespace: training-model
```
